// Writes the shared network plumbing into every HTML page of weekofdata.com.
// Reads network/network-head.html and network/network.json (generated by
// alexmercedcom/scripts/build-network-shared.mjs; never edit them by hand) and
// rewrites the content between these markers:
//   <!-- network:head:start --> ... <!-- network:head:end -->      GA4 tag, click events, Person JSON-LD
//   <!-- network:cta:start --> ... <!-- network:cta:end -->        CTA strip above the footer
//   <!-- network:footer:start --> ... <!-- network:footer:end -->  grouped network links
// It also sets twitter:site. The site has no build step, so run this before committing:
//   node scripts/apply-network.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const pages = ['index.html', 'books/index.html'];
const head = readFileSync(new URL('network/network-head.html', root), 'utf8').trim();
const { footer, cta, twitterSite } = JSON.parse(readFileSync(new URL('network/network.json', root), 'utf8'));

const esc = (v) => String(v).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const ext = ' target="_blank" rel="noopener noreferrer"';

const footerHtml = `<nav class="footer-network" aria-label="The Alex Merced Network">
${footer.groups.map((g) => `                <div class="footer-network__group">
                    <p class="footer-network__title">${esc(g.title)}</p>
                    <ul>
${g.links.map((l) => `                        <li><a href="${esc(l.url)}"${ext}>${esc(l.title)}</a></li>`).join('\n')}
                    </ul>
                </div>`).join('\n')}
            </nav>
            <p class="footer-network__all"><a href="${esc(footer.allSitesUrl)}"${ext}>${esc(footer.allSitesLabel)} &rarr;</a></p>`;

const ctaHtml = cta ? `<section class="network-cta" aria-labelledby="network-cta-heading">
        <div class="container network-cta__inner">
            <h2 id="network-cta-heading">${esc(cta.heading)}</h2>
            <div class="network-cta__links">
${cta.links.map((l, i) => `                <a class="btn ${i === 0 ? 'btn-primary' : 'btn-secondary'}" href="${esc(l.url)}"${ext} data-network-event="${esc(l.event)}">${esc(l.label)}</a>`).join('\n')}
            </div>
        </div>
    </section>` : '';

const fill = (html, name, content) => {
  const re = new RegExp(`(<!-- network:${name}:start -->)[\\s\\S]*?(\\s*<!-- network:${name}:end -->)`);
  if (!re.test(html)) throw new Error(`missing network:${name} markers`);
  return html.replace(re, `$1\n${content}$2`);
};

for (const page of pages) {
  const url = new URL(page, root);
  let html = readFileSync(url, 'utf8');
  html = fill(html, 'head', head);
  html = fill(html, 'cta', ctaHtml);
  html = fill(html, 'footer', footerHtml);
  html = html.replace(/<meta name="twitter:site" content="[^"]*">/, `<meta name="twitter:site" content="${esc(twitterSite)}">`);
  writeFileSync(url, html);
  console.log(`network applied: ${page}`);
}
